### ISSUE TITLE
Updating Firmware

### ISSUE THREAD

**Issue by mightycoco** [Befaco/midithing#10]
I'm on Windows 10

I bought the same USBasp programmer, you mentioned in the README.md

I installed the drivers with zadig-2.4.exe using libusbK drivers. The device shows up in device manager without issues

I installed the latest Arduino IDE

I copied the MIDI, Bounde2, MCP4728 folders from your repo to the libraries folder of Arduino

Opened firmware.ino - compiling works without error. I also get a firmware.ino.hex

I configured the IDE:
Board: Arduino Nano
Processor: ATMega328P
Programmer: USBasp

Sketch -> Upload using programmer gives me errors:

	Sketch uses 17628 bytes (57%) of program storage space. Maximum is 30720 bytes.
	Global variables use 1387 bytes (67%) of dynamic memory, leaving 661 bytes for local variables. Maximum is 2048 bytes.
	C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avrdude -CC:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf -v -patmega328p -cusbasp -Pusb -Uflash:w:C:\Users\xxx\AppData\Local\Temp\arduino_build_426070/firmware.ino.hex:i 

	avrdude: Version 6.3-20171130
			 Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
			 Copyright (c) 2007-2014 Joerg Wunsch

			 System wide configuration file is "C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf"

			 Using Port                    : usb
			 Using Programmer              : usbasp
			 AVR Part                      : ATmega328P
			 Chip Erase delay              : 9000 us
			 PAGEL                         : PD7
			 BS2                           : PC2
			 RESET disposition             : dedicated
			 RETRY pulse                   : SCK
			 serial program mode           : yes
			 parallel program mode         : yes
			 Timeout                       : 200
			 StabDelay                     : 100
			 CmdexeDelay                   : 25
			 SyncLoops                     : 32
			 ByteDelay                     : 0
			 PollIndex                     : 3
			 PollValue                     : 0x53
			 Memory Detail                 :

									  Block Poll               Page                       Polled
			   Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
			   ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
			   eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
			   flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
			   lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
			   hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
			   efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
			   lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
			   calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
			   signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

			 Programmer Type : usbasp
			 Description     : USBasp, http://www.fischl.de/usbasp/

	avrdude: auto set sck period (because given equals null)
	An error occurred while uploading the sketch
	avrdude: error: program enable: target doesn't answer. 1 
	avrdude: initialization failed, rc=-1
			 Double check connections and try again, or use -F to override
			 this check.

	avrdude done.  Thank you.

Executing avrdude on the command line shows this:

avrdude -C"C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf" -v -p atmega328p -c usbasp

	avrdude: Version 6.3-20171130
			 Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
			 Copyright (c) 2007-2014 Joerg Wunsch

			 System wide configuration file is "C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf"

			 Using Port                    : usb
			 Using Programmer              : usbasp
			 AVR Part                      : ATmega328P
			 Chip Erase delay              : 9000 us
			 PAGEL                         : PD7
			 BS2                           : PC2
			 RESET disposition             : dedicated
			 RETRY pulse                   : SCK
			 serial program mode           : yes
			 parallel program mode         : yes
			 Timeout                       : 200
			 StabDelay                     : 100
			 CmdexeDelay                   : 25
			 SyncLoops                     : 32
			 ByteDelay                     : 0
			 PollIndex                     : 3
			 PollValue                     : 0x53
			 Memory Detail                 :

									  Block Poll               Page                       Polled
			   Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
			   ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
			   eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
			   flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
			   lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
			   hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
			   efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
			   lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
			   calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
			   signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

			 Programmer Type : usbasp
			 Description     : USBasp, http://www.fischl.de/usbasp/

	avrdude: auto set sck period (because given equals null)
	avrdude: error: program enable: target doesn't answer. 1
	avrdude: initialization failed, rc=-1
			 Double check connections and try again, or use -F to override
			 this check.

	avrdude done.  Thank you.

What are the recommended settings to update the firmware with the same USBasp programmer you recommend in your README.md?

**Comment by xustafu** [comment]
Seems you are compiling for Arduino Nano. Please try with UNO.

**Comment by pinewavestudio** [comment]
I am having this same error message using the recommended ICSP programmer.

It seems I did not have the proper drivers installed for my USBasp.

I had to select USBasp as my programmer.  I'm leaving this note in case it helps anyone in the future.

**Comment by xustafu** [comment]
Thansk a bunch for the feedback!!

Setting the issue as solved.

**Comment by mightycoco** [comment]
Still having the same issue. Wasn't resolved for me by setting the right board.

"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avrdude" -CC:"\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf" -v -patmega328p -cusbasp -Pusb -Uflash:w:C:\Users\xxx\AppData\Local\Temp\builda3f5bb2dc51d34f6c4eeaa8f0274de71.tmp/firmware.ino.hex:i

avrdude: Version 6.3, compiled on Feb 17 2016 at 09:25:53
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf"

         Using Port                    : usb
         Using Programmer              : usbasp
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : usbasp
         Description     : USBasp, http://www.fischl.de/usbasp/

avrdude: auto set sck period (because given equals null)
avrdude: error: program enable: target doesn't answer. 1
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.


avrdude done.  Thank you.


I'm using the lates drivers from zadig 2.4, libusb-win32 1.2.6.0

**Comment by mightycoco** [comment]
Does the board has to be powered by the eurorack power supply? Couldn't find any information on this. The documentation for upgrading the firmware is lacking a lot of information and it's really quite of a hassle...

**Comment by mightycoco** [comment]
Any news on this?

**Comment by jeremybernstein** [comment]
Did you try powering the board? I'm not in my studio to check, but I think you do need a powered module in order to update the chip.

**Comment by mightycoco** [comment]
That was actually the question, because I'm unsure about that and it isn't documented. I didn't want to try powering the module in my rack along connecting the programmer before I blow things up.

I'm a noob in flashing firmwares to modules and there are different conflicting documentations to be found online. I'm really missing a detailed step-by-step guide for the average musician...

**Comment by jeremybernstein** [comment]
I hear you. You won't blow anything up, I promise. Give that a try, please.

**Comment by starmandeluxe** [comment]
I am having the same issue actually, and I do have the module powered on, the pin orientation is correct, and also using USBasp with the fixed libusbK driver to program. I am getting this output:

`Arduino: 1.8.8 (Windows 10), TD: 1.45, Board: "Arduino Uno"

Sketch uses 18224 bytes (56%) of program storage space. Maximum is 32256 bytes.
Global variables use 1397 bytes (68%) of dynamic memory, leaving 651 bytes for local variables. Maximum is 2048 bytes.
C:\Users\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/bin/avrdude -CC:\Users\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf -v -patmega328p -cusbasp -Pusb -Uflash:w:C:\Users\AppData\Local\Temp\arduino_build_193372/firmware.ino.hex:i 

avrdude: Version 6.3, compiled on Feb 17 2016 at 09:25:53
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Users\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf"

         Using Port                    : usb
         Using Programmer              : usbasp
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : usbasp
         Description     : USBasp, http://www.fischl.de/usbasp/

avrdude: auto set sck period (because given equals null)
avrdude: warning: cannot set sck period. please check for usbasp firmware update.
avrdude: error: program enable: target doesn't answer. 1 
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.


avrdude done.  Thank you.

the selected serial port 
 does not exist or your board is not connected
`

Any ideas?
