### ISSUE TITLE
Error compiling firmware v.2

### ISSUE THREAD

**Issue by mihozu** [Befaco/midithing#11]
Hello,

I'm trying to upgrade my midi thing with firmware v.2.
I'm however encountering an issue when compiling the code, seems an error with the mcp4728 library :

firmware:50:1: error: 'mcp4728' does not name a type
 mcp4728 Dac = mcp4728(0); // instantiate mcp4728 object, Device ID = 0
 ^
/Users/mihozu/Documents/Arduino/firmware/firmware.ino: In function 'void setup()':
firmware:108:3: error: 'Dac' was not declared in this scope
   Dac.begin();  // initialize i2c interface
   ^
/Users/mihozu/Documents/Arduino/firmware/firmware.ino: In function 'void SendvaltoDAC(unsigned int, unsigned int)':
firmware:268:3: error: 'Dac' was not declared in this scope
   Dac.analogWrite(port, val); // write to input register of a DAC. Channel 0-3, Value 0-4095
   ^
exit status 1
'mcp4728' does not name a type

I wonder if I have the right mcp4728 library version,
the arduino library manager shows version 0.1.0

**Comment by xustafu** [comment]
That might be the case. did you tried downloading the library and adding it manually?

**Comment by max-circlefade** [comment]
Same here
Edit: that is because the mcp lib is not the one in the arduino lib folder, rather the one here
https://code.google.com/archive/p/neuroelec/downloads
Now it works perfectly
Delete the mcp lib you downloaded in the IDE (by removing its folder) and add this new one manually (using the add .zip lib)
You need to unzip the file downloaded in the link, then zip the mcp4728 subfolder

**Comment by thomasemilhansen** [comment]
You also have to change line 65 in firmware.ino to "struct MIDISettings : public midi::DefaultSerialSettings" if you're using the latest version of the MIDI library (as per November 2021).

**Comment by xustafu** [comment]
Updated instructions to reflect more clearly MCP library link.
Updated code to be compatible with MIDI v5.0.2
check commit: bb1d248833699629d1fd6051b6b829063734ed91
