### ISSUE TITLE
Documentation bug regarding ST/SP behavior

### ISSUE THREAD

**Issue by ihatetoregister** [Befaco/midithing#13]
The documentation section for setting ST/SP mode (page 6) mentions to send #7 for Reset mode and #8 for ST/SP mode. But the image on page 5 say #9 for ST/SP mode which is the correct value. Please also clarify that it should be received on channel 2 in the section on page 6.

**Comment by xustafu** [comment]
Checking this one. Will be back with update the soonest!

**Comment by xustafu** [comment]
Documentation updated and uploaded to our website:

https://www.befaco.org/docs/MIDI%20Thing/Midi_Thing%20_V2_User_Manual.pdf
