### ISSUE TITLE
Avrdude failing to connect to USBasp programmer

### ISSUE THREAD

**Issue by starmandeluxe** [Befaco/midithing#15]
I am having a very similar issue as in https://github.com/Befaco/midithing/issues/10

I do have the module powered on, the pin orientation is correct, and also using USBasp with the fixed libusbK driver to program. I am getting this output:

```Arduino: 1.8.8 (Windows 10), TD: 1.45, Board: "Arduino Uno"

Sketch uses 18224 bytes (56%) of program storage space. Maximum is 32256 bytes.
Global variables use 1397 bytes (68%) of dynamic memory, leaving 651 bytes for local variables. Maximum is 2048 bytes.
C:\Users\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/bin/avrdude -CC:\Users\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf -v -patmega328p -cusbasp -Pusb -Uflash:w:C:\Users\AppData\Local\Temp\arduino_build_193372/firmware.ino.hex:i

avrdude: Version 6.3, compiled on Feb 17 2016 at 09:25:53
Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
Copyright (c) 2007-2014 Joerg Wunsch

     System wide configuration file is "C:\Users\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf"

     Using Port                    : usb
     Using Programmer              : usbasp
     AVR Part                      : ATmega328P
     Chip Erase delay              : 9000 us
     PAGEL                         : PD7
     BS2                           : PC2
     RESET disposition             : dedicated
     RETRY pulse                   : SCK
     serial program mode           : yes
     parallel program mode         : yes
     Timeout                       : 200
     StabDelay                     : 100
     CmdexeDelay                   : 25
     SyncLoops                     : 32
     ByteDelay                     : 0
     PollIndex                     : 3
     PollValue                     : 0x53
     Memory Detail                 :

                              Block Poll               Page                       Polled
       Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
       ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
       eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
       flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
       lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
       hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
       efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
       lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
       calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
       signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

     Programmer Type : usbasp
     Description     : USBasp, http://www.fischl.de/usbasp/
avrdude: auto set sck period (because given equals null)
avrdude: warning: cannot set sck period. please check for usbasp firmware update.
avrdude: error: program enable: target doesn't answer. 1
avrdude: initialization failed, rc=-1
Double check connections and try again, or use -F to override
this check.

avrdude done. Thank you.

the selected serial port
does not exist or your board is not connected
```

Any ideas?

**Comment by xustafu** [comment]
Make sure USBasp pinout matches MIDI thing ICSP pinout:

https://befaco.org/docs/MIDI_Thing/Midi_Thing%20_V1_Schematic.pdf

**Comment by xustafu** [comment]
Oh! Just read you doublechecked already the pinout sorry!! 
Can you send me pics of the programmer you got?

**Comment by starmandeluxe** [comment]
@xustafu, sure. Here is the front and back:

![IMG_20200830_204252](https://user-images.githubusercontent.com/1654255/91658144-983f4780-eb01-11ea-9d09-cdee5f9af415.jpg)
![IMG_20200830_204337](https://user-images.githubusercontent.com/1654255/91658147-9e352880-eb01-11ea-87c9-a2b4f4f67b0e.jpg)

**Comment by xustafu** [comment]
Programemr looks like the one we use here. What about voltage jumper. Is it set to 5v?
On Arduino, are you using the option sketch > Upload using programmer?
In module side. Can you check that pins from the connector has continuity to the relevant pin in the uController?

**Comment by starmandeluxe** [comment]
@xustafu Thanks for checking.

Jumper is set to 5v. I'm using "upload using programmer". I have confirmed continuity with all 6 pins from programmer to module side. 

Not sure what else could be the issue... By the way I have v1 of the module. Maybe I need an older firmware and not the latest commit? Or maybe I can just purchase the preloaded firmware IC and I can use it? Actually my module seems to be bugged out and won't respond to button press or midi, startup sequence doesn't run either. It starts up with LEDs 1, 2, and 4 lit and then goes dark. It was working fine until a couple days ago. So that's why I am trying to reprogram it.

**Comment by xustafu** [comment]
There is a chance the MCU is fried. Try burning the bootloader first... maybe its that? If not, you can get a new one in Akihabara and flash it.
If that fails, you can always get a new one pre-programmer from us... but would not like to spoil the fun from you :D

**Comment by starmandeluxe** [comment]
Thanks a bunch @xustafu. I'm gonna close this for now, I'll try resetting bootloader and if that doesn't work I'll see if I can replace the part :)

**Comment by starmandeluxe** [comment]
Just to follow-up, I bought a new Atmega328, replaced it in the module, flashed the bootloader, and then loaded the latest firmware, and now the module is back in business again!!!! It was exactly like you said :) 
So if anyone else sees the error "the selected serial port does not exist or your board is not connected" and if you tried everything else, the hardware may be the issue. Thank you!
