### ISSUE TITLE
MIDI Thing v2

### ISSUE THREAD

**Issue by lateshift** [Befaco/midithing#18]
Heya!

Are the MIDI Thing v2 sources "hiding" in here?

Thanks 👏 ✌️
Jens

**Comment by xustafu** [comment]
Nope!
This is MIDI Thing 1 code :)
MIDI Thing 2 will come after module is released!

**Comment by lateshift** [comment]
Yeah just saw the post on instagram ... my bad ... Thanks for the heads up! ✊
