### ISSUE TITLE
Drop Bounce in favor of Bounce2

### ISSUE THREAD

**Issue by dvzrv** [Befaco/midithing#3]
The Bounce library is EOL and should be dropped in favor of Bounce2 (https://github.com/thomasfredericks/Bounce2).
We need patches and testing for doing that.

**Comment by feelingweird** [comment]
Hi, 
When i looked at the code, this appears to have been done,. 

is that correct?

**Comment by jeremybernstein** [comment]
Yeah, long changed. Let's close this ticket.

**Comment by mightycoco** [comment]
You should mention this in the README.md for upgrading the firmware.

**Comment by xustafu** [comment]
readme.md updated!
