### ISSUE TITLE
Learned lowest note is ignored

### ISSUE THREAD

**Issue by lijon** [Befaco/midithing#6]
When learning the lowest note, this note is then ignored. For example when learning the lowest C on a keyboard, it will then only recognize notes from C# and up.

Perhaps change https://github.com/Befaco/midithing/blob/master/firmware/MIDIClass.ino#L270 to do `minInput <= pitch` instead?

**Comment by xustafu** [comment]
Checking this option.
The change suggested do work, so after learning first note is actually used. 
Need some doublechecking as voltage for the first note is not consistent (~20mV)

**Comment by lijon** [comment]
Perhaps it results in wrong index (-1 or so) at some other stage for table lookup, reading outside the array?
