### ISSUE TITLE
Not possible to calibrate/tune lowest note

### ISSUE THREAD

**Issue by tangram** [Befaco/midithing#7]
Background: I have sequencers that cannot be tuned. To avoid having to constantly retune oscillators, I'd want one of these sequencers to be the reference, so that e.g. C4 on the sequencer equals C4 from the Midi Thing.

The Midi Thing is very tunable, no problem. But say I set the lowest note at B0, to be able to play from C1 and up (see issue #6). Calibration points are now at B0, F1, B1 and so on. But B0 is not tunable, as B0 and A#0 are out of range even when calibrating, resulting in a curve that goes very sharp or very flat from F1 and down to C1.

I realize that it wouldn't make sense to tune below 0V, but the lowest note is actually 0.333V on my multimeter. I realize also that this is a common problem with a modular setup, but allowing the lower note to be tuned on the Midi Thing can alleviate this somewhat.

Any input on this issue?

**Comment by xustafu** [comment]
Hi there!

Sorry for the delayed reply! Check branch development for a solution for the lowest note not being learnt.
About minimum voltage, this is a know behaviour of the DAC, it never goes down to zero. But 0.3 v is actually quite high!

**Comment by tangram** [comment]
Alright, thanks. I've been using the develop branch for the last month or so (from the last round of commits), although I haven't investigated this issue again. I'll do another update and see where it stands now.
