### ISSUE TITLE
The clock is delayed by full cycle in the beginning.

### ISSUE THREAD

**Issue by Afterisk** [Befaco/midithing#8]
Hello guys,
usually the first clock tick hits together with the start, that's what I've experienced with other clock generators/midi converters, however here on MidiThing it waits the full cycle. I've found the source of behavior, it's in the HandleMIDI class. 

Basically in HandleStart/HandleContinue methods the clock count should not be set to "0", but instead to ppq value, that way the clock will hit first time right when you press play on the sequencer.

countCLOCK = ppqnCLOCK; // was countCLOCK = 0;

**Comment by numelar** [comment]
Hi Afterisk, I'm the developer of the last modifications posted in develop branch.
First of all, thank you for the test, code check and the information provided, very appreciated :)
We will check and test this issue ASAP.
Please, keep rocking the module!
