### ISSUE TITLE
Atmega328p chip substitution method doesn't work

### ISSUE THREAD

**Issue by dsanz006** [Befaco/midithing#9]
so I bought an Arduino Uno and replaced its Atmega328p chip with the one in the Midi Thing, in order to update its firmware to V2. In the Arduino IDE the project compiles correctly, but when I try to upload it to the board I get the following errors: 

`avrdude: stk500_recv(): programmer is not responding`
`avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00`
`avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0xf8`
`avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0xc0`
`avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xf8`
`avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x80`
`avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xf8`
`avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x80`
`avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x00`
`avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xf8`
`avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xc0`
`Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.`

However if I try it with the Atmega chip that came with the Arduino Uno board, everything is fine. So it seems to be something about the Atmega chip on the Midi Thing module.

I would really like to solve this, otherwise I am left with a useless Arduino Uno, with no Atmega328p chip.

**Comment by xustafu** [comment]
This method will not work if Arduino bootloader was not loaded into MIDI thing.
This method slipped into v2 docu and should not be there. Sorry!!!

Please try using an external programmer, or a protoboard and Arduino as ISP sketch to load the program.

**Comment by xustafu** [comment]
Setting as solved after  no feedback received.
